### ISSUE TITLE
Wyam still running on .Net Core 2.1 which is end of support as of August 21st 2021

### ISSUE THREAD

**Issue by Franklin89** [Wyamio/Wyam#26]
.NET Core 2.1 has End of support on August 21st. What would the effort be to update to .NET 5 or 6? 

https://dotnet.microsoft.com/download/dotnet

**Comment by daveaglick** [comment]
There are no plans to update Wyam at this time, the project is essentially archived. The successor project is [Statiq](https://github.com/statiqdev) which currently supports more recent .NET Core runtimes and has been under active development for years (soon to go 1.0). It can be thought of as a version-next of Wyam, but enough has changed that it made sense to make a clean break and rebrand everything. That said, Wyam should continue to run under more recent .NET versions - even though the packages are compiled using an older SDK, .NET is very good about maintaining backwards compatibility.
