### ISSUE TITLE
Update Cake.Wyam add-in to target Cake v2.0.0

### ISSUE THREAD

**Issue by augustoproiete** [Wyamio/Wyam#28]
[Cake 2.0.0](https://cakebuild.net/blog/2021/11/cake-v2.0.0-released) has been released  🎉

**Comment by daveaglick** [comment]
Done, and the NuGet package has been updated:
https://www.nuget.org/packages/Cake.Wyam/2.2.13

Also 👀
![image](https://user-images.githubusercontent.com/1020407/144911682-c0edd023-4fdc-48b1-8cd8-93867c9c3acd.png)

Cake.Wyam has been downloaded more times than Wyam itself, which is a little bit 🤔.

**Comment by augustoproiete** [comment]
Thanks @daveaglick !

Impressive numbers! I'm guessing the Cake website build is contributing somewhat to that, but still huge!

ps: I noticed you only added `netcoreapp3.1`. Any reason not to [multi-target `net5.0` and `net6.0`](https://cakebuild.net/docs/extending/addins/best-practices) as well?

**Comment by gep13** [comment]
@daveaglick more times that both Wyam and Wyam.Tool?

**Comment by daveaglick** [comment]
@gep13 - yeah, Wyam.Tool is at around 50k while Wyam is only at around 150k compared to Cake.Wyam at 173k. Though I guess Wyam and Wyam.Tool combined are still higher. Thankfully it's falling off, which I think/hope represents people slowly migrating.

@augustoproiete 
> Any reason not to multi-target net5.0 and net6.0 as well

Yes! Laziness and a desire to get the update out as quickly as possible while spending as little time as possible in this old codebase :)
